# paths:
#   /cars:
#     post:
#       summary: create product
#       security:
#         - BearerAuth: []
#       tags:
#         - Cars
#       consumes:
#         - multipart/form-data
#       requestBody:
#         required: true
#         content:
#           multipart/form-data:
#             schema:
#               $ref: "#/components/schemas/Cars"
#       produces:
#         -  multipart/form-data
#       responses:
#         200:
#           description: An array of user data
#           content:
#             "application/json":
#               schema:
#                 allOf:
#                   - $ref: "#/components/schemas/JsendSuccess"
#                   - properties:
#                       data:
#                         type: array
#                         items:
#                           allOf:
#                             - properties:
#                                 id:
#                                   type: integer
#                             - $ref: "#/components/schemas/Cars"
  
#     get:
#       summary: Get all cars
#       tags: 
#         - Cars
#       consumes:
#         - application/json
#       responses:
#         200:
#           description: An array of Cars list
#           content:
#             "application/json":
#               schema:
#                 allOf:
#                   - $ref: "#/components/schemas/JsendSuccess"
#                   - properties:
#                       data:
#                         type: array
#                         items:
#                           allOf:
#                             - properties:
#                                 id:
#                                   type: integer
#                             - $ref: "#/components/schemas/Cars"
#   /cars/{id}:
#     get:
#       summary: Get cars by id
#       tags: 
#         - Cars
#       consumes:
#         - application/json
#       parameters:
#         - in: path
#           name: id
#           schema:
#             type: integer
#           required: true
#           description: Numeric ID of the Cars to get
#       responses:
#         200:
#           description: An array of Cars list
#           content:
#             "application/json":
#               schema:
#                 allOf:
#                   - $ref: "#/components/schemas/JsendSuccess"
#                   - properties:
#                       data:
#                         type: array
#                         items:
#                           allOf:
#                             - properties:
#                                 id:
#                                   type: integer
#                             - $ref: "#/components/schemas/Cars"
#     put:
#       summary: update cars
#       tags: 
#         - Cars
#       consumes:
#         - application/json
#       parameters:
#         - in: path
#           name: id
#           schema:
#             type: integer
#           required: true
#           description: Numeric ID of the Cars to get
#       security:
#         - BearerAuth: []
#       requestBody:
#         required: true
#         content:
#           multipart/form-data:
#             schema:
#               $ref: "#/components/schemas/Cars"
#       produces:
#         -  multipart/form-data
#       responses:
#         200:
#           description: An array of user data
#           content:
#             "application/json":
#               schema:
#                 allOf:
#                   - $ref: "#/components/schemas/JsendSuccess"
#                   - properties:
#                       data:
#                         type: array
#                         items:
#                           allOf:
#                             - properties:
#                                 id:
#                                   type: integer
#                             - $ref: "#/components/schemas/Cars"
#     delete:
#       summary: delete cars
#       tags: 
#         - Cars
#       consumes:
#         - application/json
#       security:
#         - BearerAuth: []
#       parameters:
#         - in: path
#           name: id
#           schema:
#             type: integer
#           required: true
#           description: Numeric ID of the Cars to get
#       responses:
#         200:
#           description: An array of Cars list
#           content:
#             "application/json":
#               schema:
#                 allOf:
#                   - $ref: "#/components/schemas/JsendSuccess"
#                   - properties:
#                       data:
#                         type: array
#                         items:
#                           allOf:
#                             - properties:
#                                 id:
#                                   type: integer